# Generated by Django 3.0.6 on 2020-07-25 04:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('unit', models.CharField(choices=[('шт', 'шт'), ('час', 'час')], default='час', max_length=20)),
                ('type_of_nomenclature', models.CharField(choices=[('услуга', 'услуга'), ('товар', 'товар')], default='час', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('денег нету', 'денег нету длинный шмель'), ('всё узнал', 'всё знаю!')], default='денег нету', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('surname', models.CharField(max_length=127)),
                ('name', models.CharField(max_length=127)),
                ('active', models.BooleanField()),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.Reason')),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
            ],
        ),
    ]
