# Generated by Django 3.0.6 on 2020-07-25 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=15)),
                ('cource', models.CharField(max_length=63)),
                ('level', models.CharField(max_length=15)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('teacher', models.CharField(default='guessing', max_length=127)),
            ],
        ),
    ]
