# Generated by Django 3.0.6 on 2020-05-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.CharField(default='guessing', max_length=127),
        ),
    ]
